"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict false.");
console.log(car == 'honda');
console.log("Is car == 'subaru? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'mazda'? I predict false.");
console.log(car == 'mazda');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'BMW'? I predict false.");
console.log(car == 'BMW');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'audi');
console.log("Is car == 'mercedes'? I predict false.");
console.log(car == 'mercedes');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'daihatsu'? I predict false.");
console.log(car == 'daihatsu');
console.log("Is car == 'oggy'? I predict True.");
console.log(car == 'oggy');
