"use strict";
const str1 = "Hello";
const str2 = "hello";
console.log(str1 == str2);
console.log(str1 !== str2);
const text1 = "Hello world";
const text2 = "hello world";
console.log(text1.toLowerCase() === text2);
const num1 = 10;
const num2 = 5;
console.log(num1 === num2);
console.log(num1 !== num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
const l = 5;
const y = 10;
const z = 15;
console.log(l < y && y < z);
console.log(l < y || y > z);
console.log(l > y && y > z);
console.log(l > y || y > z);
const fruits = ['apple', 'grapes', 'orange', 'banana'];
console.log(fruits.includes('banana'));
console.log(fruits.includes('kiwi'));
const colors = ['yellow', 'purple', 'green', 'blue'];
console.log(!colors.includes('brown'));
console.log(!colors.includes('blue'));
